import type { Metadata } from 'next';
import NavOverlay from './components/NavOverlay';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavOverlay />
        {children}
      </body>
    </html>
  );
}
